require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActivitesController do

  # This should return the minimal set of attributes required to create a valid
  # Activite. As you add validations to Activite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActivitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all activites as @activites" do
      activite = Activite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:activites).should eq([activite])
    end
  end

  describe "GET show" do
    it "assigns the requested activite as @activite" do
      activite = Activite.create! valid_attributes
      get :show, {:id => activite.to_param}, valid_session
      assigns(:activite).should eq(activite)
    end
  end

  describe "GET new" do
    it "assigns a new activite as @activite" do
      get :new, {}, valid_session
      assigns(:activite).should be_a_new(Activite)
    end
  end

  describe "GET edit" do
    it "assigns the requested activite as @activite" do
      activite = Activite.create! valid_attributes
      get :edit, {:id => activite.to_param}, valid_session
      assigns(:activite).should eq(activite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Activite" do
        expect {
          post :create, {:activite => valid_attributes}, valid_session
        }.to change(Activite, :count).by(1)
      end

      it "assigns a newly created activite as @activite" do
        post :create, {:activite => valid_attributes}, valid_session
        assigns(:activite).should be_a(Activite)
        assigns(:activite).should be_persisted
      end

      it "redirects to the created activite" do
        post :create, {:activite => valid_attributes}, valid_session
        response.should redirect_to(Activite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved activite as @activite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activite.any_instance.stub(:save).and_return(false)
        post :create, {:activite => { "titre" => "invalid value" }}, valid_session
        assigns(:activite).should be_a_new(Activite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activite.any_instance.stub(:save).and_return(false)
        post :create, {:activite => { "titre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested activite" do
        activite = Activite.create! valid_attributes
        # Assuming there are no other activites in the database, this
        # specifies that the Activite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Activite.any_instance.should_receive(:update).with({ "titre" => "MyString" })
        put :update, {:id => activite.to_param, :activite => { "titre" => "MyString" }}, valid_session
      end

      it "assigns the requested activite as @activite" do
        activite = Activite.create! valid_attributes
        put :update, {:id => activite.to_param, :activite => valid_attributes}, valid_session
        assigns(:activite).should eq(activite)
      end

      it "redirects to the activite" do
        activite = Activite.create! valid_attributes
        put :update, {:id => activite.to_param, :activite => valid_attributes}, valid_session
        response.should redirect_to(activite)
      end
    end

    describe "with invalid params" do
      it "assigns the activite as @activite" do
        activite = Activite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activite.any_instance.stub(:save).and_return(false)
        put :update, {:id => activite.to_param, :activite => { "titre" => "invalid value" }}, valid_session
        assigns(:activite).should eq(activite)
      end

      it "re-renders the 'edit' template" do
        activite = Activite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activite.any_instance.stub(:save).and_return(false)
        put :update, {:id => activite.to_param, :activite => { "titre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested activite" do
      activite = Activite.create! valid_attributes
      expect {
        delete :destroy, {:id => activite.to_param}, valid_session
      }.to change(Activite, :count).by(-1)
    end

    it "redirects to the activites list" do
      activite = Activite.create! valid_attributes
      delete :destroy, {:id => activite.to_param}, valid_session
      response.should redirect_to(activites_url)
    end
  end

end
